application: imyp
version: 3
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  
- url: /robots.txt
  static_files: static/images/robots.txt
  upload: static/images/robots.txt
  
- url: /.*
  script: main.py
  